# Generated by Django 6.1.1 on 2026-09-26 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('white', models.CharField(max_length=200)),
                ('black', models.CharField(max_length=200)),
                ('white_elo', models.IntegerField(blank=True, null=True)),
                ('black_elo', models.IntegerField(blank=True, null=True)),
                ('result', models.CharField(choices=[('1-0', 'White wins'), ('0-1', 'Black wins'), ('1/2-1/2', 'Draw')], max_length=10)),
                ('event', models.CharField(blank=True, max_length=300)),
                ('site', models.CharField(blank=True, max_length=300)),
                ('date_played', models.CharField(blank=True, max_length=20)),
                ('source_label', models.CharField(blank=True, max_length=200)),
                ('moves', models.JSONField(help_text='Full move list in SAN.')),
                ('pgn_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PositionNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('san', models.CharField(blank=True, help_text='Move (SAN) that led from the parent to this node.', max_length=16)),
                ('ply', models.PositiveIntegerField(default=0)),
                ('fen', models.CharField(max_length=100)),
                ('total_games', models.PositiveIntegerField(default=0)),
                ('white_wins', models.PositiveIntegerField(default=0)),
                ('draws', models.PositiveIntegerField(default=0)),
                ('black_wins', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='explorer.positionnode')),
                ('sample_games', models.ManyToManyField(blank=True, help_text='Only populated for positions at or below the low-sample threshold.', related_name='position_nodes', to='explorer.game')),
            ],
            options={
                'indexes': [models.Index(fields=['parent', 'san'], name='explorer_po_parent__f37e8f_idx')],
                'unique_together': {('parent', 'san')},
            },
        ),
    ]
